cc_library(
    name = "head",
    srcs = [
        "msg_head.cc",
        "msg_wrapper.cc",
    ],
    incs = [
        ".",
        "../../thirdparty/protobuf/src",
    ],
    deps = [
        "//thirdparty/protobuf/src/google/protobuf:protobuf",
    ],
)
