cc_library(
    name = "head",
    srcs = [
        "msg_head.cc",
        "msg_wrapper.cc",
    ],
    incs = [
        ".",
        "../../thirdparty/protobuf-3.6.x/src",
    ],
    deps = [
        "//thirdparty/protobuf:protobuf",
    ],
)
