cc_binary(
    name = 'chat_svr',
    srcs = [
        'main.cpp',
    ],
    incs = [
        '../../thirdparty/glog/src/glog',
    ],
    deps = [
        '//thirdparty/glog/src:glog',
    ],
)
