cc_binary(
    name = 'chat_svr',
    srcs = [
        'main.cpp',
    ],
    incs = [
        '../../thirdparty/glog/src/glog',
        '../../thirdparty/glog/src',
        '../../common/network',
    ],
    deps = [
        '//thirdparty/glog/src:glog',
        '//common/network:network',
    ],
)
