cc_binary(
    name = "chat_cli",
    srcs = [
        'main.cc',
        'chat_cli_cfg.cc',
        'chat_cli.cc',
    ],
    incs = [
        '../../common/config',
        '../../thirdparty/glog/src/glog',
    ],
    deps = [
        '//common/config:config',
        '//thirdparty/glog/src:glog',
    ],
)
